mqtt:
  host: broker.emqx.io
  port: 1883
  client-id: mqtt-panel-demo
  topic-prefix: sourcesimian/mqtt-panel/demo
  # auth:
  #   type: basic
  #   username: "user"
  #   password: "password"

http:
  bind: 0.0.0.0
  port: 8080
  max-connections: 10
  log-level: INFO

# auth:
#   users:
#   - username: admin
#     password: admin

logging:
  level: INFO

cache:
  root: data/cache

panels:
  - title: Example
    name: example
    icon: home
    groups:
    - example_mood
    - example_inside
    - example_outside
    - example_irrigation
    - example_pool
    - example_audio
    - example_cameras
    - example_image

  - title: Widgets
    name: widgets
    icon: widgets
    groups:
      - widget_button_text
      - widget_light
      - widget_switch
      - widget_gauge
      - widget_select
      - widget_slider
      - widget_slider_live
      - widget_image
      - widget_iframe
      - widget_reuse

  # - title: Play
  #   icon: toys
  #   groups:
  #   - play_buttons
  #   - play_switch_light
  #   - play_switch_multi
  #   - play_feedback
  #   - play_gauge
  #   - play_reuse
  #   - play_select
  #   - play_image
  #   - play_iframe


groups:
  - title: Mood
    name: example_mood
    widgets:

    - title: All
      type: button
      publish: example/mood/lights
      payload: ALL-OFF
      text: "OFF"
      icon: bedtime
      color: "#b81212"
      confirm: "Switch all off?"
      qos: 1
      retain: True

    - title: Outside
      type: button
      publish: example/mood/lights
      payload: OUTSIDE-ON
      text: "ON"
      icon: power_settings_new
      color: "#008000"
      qos: 1
      retain: True

    - title: Event
      type: button
      publish: example/mood/lights
      payload: EARLY
      text: "Early"
      icon: nights_stay
      color: "#008000"
      qos: 1
      retain: True

    - title: Mode
      type: text
      subscribe: example/mood/lights
      color: "#FFF"

  # ---------------------------------------------------------------------------
  - title: Inside
    name: example_inside
    widgets:

    - title: Stairs
      type: switch
      publish: example/stairs-light
      subscribe: example/stairs-light
      values:
      - payload: OFF
        text: off
        icon: light
      - payload: ON
        text: ON
        icon: light
      qos: 1
      cache: True

    - title: Kitchen
      type: switch
      publish: example/kitchen-light
      subscribe: example/kitchen-light
      values:
      - payload: OFF
        text: off
        icon: light
      - payload: ON
        text: ON
        icon: light
      qos: 1
      cache: True

    - title: Scullery
      type: switch
      publish: example/scullery-light
      subscribe: example/scullery-light
      values:
      - payload: OFF
        text: off
        icon: light
      - payload: ON
        text: ON
        icon: light
      qos: 1
      cache: True

    - title: Garage
      type: switch
      publish: example/garage-light
      subscribe: example/garage-light
      values:
      - payload: OFF
        text: off
        icon: light
      - payload: ON
        text: ON
        icon: light
      qos: 1
      cache: True

  # ---------------------------------------------------------------------------
  - title: Outside
    name: example_outside
    widgets:

    - title: Buddha Light
      type: switch
      publish: example/buddha-light
      subscribe: example/buddha-light
      values:
      - payload: OFF
        text: off
        icon: light_mode
      - payload: ON
        text: ON
        icon: light_mode
      qos: 1
      cache: True

    - title: Nandina Light
      type: switch
      publish: example/nandina-light
      subscribe: example/nandina-light
      values:
      - payload: OFF
        text: off
        icon: light_mode
      - payload: ON
        text: ON
        icon: light_mode
      qos: 1
      cache: True

    - title: Greenbelt
      type: switch
      publish: example/greenbelt-light
      subscribe: example/greenbelt-light
      values:
      - payload: OFF
        text: off
        icon: light_mode
      - payload: ON
        text: ON
        icon: light_mode
      qos: 1
      cache: True

    - title: Front
      type: switch
      publish: example/front-light
      subscribe: example/front-light
      values:
      - payload: OFF
        text: off
        icon: light
      - payload: ON
        text: ON
        icon: light
      qos: 1
      cache: True

  # ---------------------------------------------------------------------------
  - title: Accessories
    name: example_accessories
    widgets:
    - title: Cat Blanket
      type: switch
      publish: example/cat-blanket
      subscribe: example/cat-blanket
      values:
      - payload: OFF
        text: off
        icon: pets
      - payload: ON
        text: ON
        icon: pets
      qos: 1
      cache: True

    - title: Jeeves
      type: switch
      publish: example/jeeves-switch
      subscribe: example/jeeves-switch
      values:
      - payload: OFF
        text: off
        icon: smart_toy
      - payload: ON
        text: ON
        icon: smart_toy
      qos: 1
      cache: True

  # ---------------------------------------------------------------------------
  - title: Irrigation
    name: example_irrigation
    widgets:

    - title: Mode
      type: switch
      publish: example/irrigation-mode
      subscribe: example/irrigation-mode
      values:
      - text: "Calendar"
        payload: "AUTO"
        icon: motion_photos_auto
        color: '#40C0C0'
      - text: "Manual"
        payload: "MANUAL"
        icon: fiber_manual_record
        color: '#66c040'
      qos: 1
      retain: True

    - title: Source
      type: select
      publish: example/irrigation-source
      subscribe: example/irrigation-source
      values:
      - text: "Off"
        payload: "CLOSED"
        icon: stop_circle
        color: '#8A8A8A'
      - text: "Main"
        payload: "MAIN"
        icon: play_circle_outline
        color: '#149cf7'
      - text: "Dam"
        payload: "DAM"
        icon: play_circle_outline
        color: '#946618'
      qos: 1
      retain: True

    - title: Irrigation Front
      type: switch
      publish: example/irrigation-front
      subscribe: example/irrigation-front
      values:
      - payload: OFF
        text: off
        icon: water_drop
      - payload: ON
        text: ON
        icon: water_drop
        color: cyan
      qos: 1
      retain: True

    - title: Irrigation Back
      type: switch
      publish: example/irrigation-back
      subscribe: example/irrigation-back
      values:
      - payload: OFF
        text: off
        icon: water_drop
      - payload: ON
        text: ON
        icon: water_drop
        color: cyan
      qos: 1
      retain: True

    - title: Irrigation Beds
      type: switch
      publish: example/irrigation-beds
      subscribe: example/irrigation-beds
      values:
      - payload: OFF
        text: off
        icon: water_drop
      - payload: ON
        text: ON
        icon: water_drop
        color: cyan
      qos: 1
      retain: True

  - title: Pool
    name: example_pool
    widgets:

    - title: Mode
      type: switch
      publish: example/pool-pump-mode
      subscribe: example/pool-pump-mode
      values:
      - text: "Calendar"
        payload: "AUTO"
        icon: motion_photos_auto
        color: '#40C0C0'
      - text: "Manual"
        payload: "MANUAL"
        icon: fiber_manual_record
        color: '#66c040'
      qos: 1
      retain: True

    - title: Pump
      type: switch
      publish: example/pool-pump
      subscribe: example/pool-pump
      values:
      - payload: OFF
        text: off
        icon: replay_circle_filled
        confirm: "Switch Pool Pump OFF?"
      - payload: ON
        text: ON
        icon: replay_circle_filled
        color: "#00C000"
        confirm: "Switch Pool Pump ON?"
      qos: 1
      retain: True

  - title: Audio
    name: example_audio
    widgets:

    - title: Volume
      type: slider
      publish: example/volume
      subscribe: example/volume
      live: True
      ranges:
      - range: [0, 10]
        text: "Shhh"
        icon: volume_off
        color: "#00c000"
      - range: [10, 30]
        text: "Chill"
        icon: volume_mute
        color: "#02b002"
      - range: [30, 70]
        text: "Vibe"
        icon: volume_down
        color: "#82b002"
      - range: [70, 90]
        text: "Party"
        icon: volume_up
        color: "#b08a02"
      - range: [90, 100]
        text: "Ouch"
        icon: volume_up
        color: "#b03c02"
      qos: 1
      retain: True

    - title: Sound
      type: gauge
      subscribe: example/volume
      ranges:
      - range: [0, 10]
        text: "Quiet"
        icon: volume_off
        color: "#00c000"
      - range: [10, 30]
        text: "Gentle"
        icon: volume_mute
        color: "#02b002"
      - range: [30, 70]
        text: "Medium"
        icon: volume_down
        color: "#82b002"
      - range: [70, 90]
        text: "Noisy"
        icon: volume_up
        color: "#b08a02"
      - range: [90, 100]
        text: "Loud"
        icon: volume_up
        color: "#b03c02"
      qos: 1
      cache: True

  - title: Cameras
    name: example_cameras
    widgets:
    - title: Source
      type: select
      publish: example/camera
      values:
      - text: "Cape Town"
        payload: "https://www.i-traffic.co.za/map/Cctv/WC%20CCTV%20N1%20803--4"
        icon: videocam
        color: cyan
      - text: "Huguenot Tunnel"
        payload: "https://www.i-traffic.co.za/map/Cctv/WC%20CCTV%20N1%20146--4"
        icon: videocam
        color: magenta
      - text: "Sir Lowry's Pass"
        payload: "https://www.i-traffic.co.za/map/Cctv/WC%20CCTV%20N2%20269--4"
        icon: videocam
        color: green
      - text: "Other"
        payload: "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1&mute=1"
        icon: videocam
        confirm: "Select Other?"
      qos: 1
      retain: True
      cache: True

    - title: Iframe
      type: iframe
      subscribe: example/camera
      refresh: 300
      attr:
        src:
        width: 320px
        height: 240px

  # --- group: Image ---
  - title: Image
    name: example_image
    widgets:
    - title: Source
      type: select
      publish: example/image/src
      values:
      - text: "Cape Town"
        payload: "https://upload.wikimedia.org/wikipedia/commons/d/dc/Table_Mountain_DanieVDM.jpg"
        icon: image
      - text: "Venice"
        payload: "https://upload.wikimedia.org/wikipedia/commons/1/1d/License_Free_Photo_-_Creative_Commons_by_gnuckx_%2811645325224%29.jpg"
        icon: image
      - text: "Ireland"
        payload: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Glendalough.jpg/1920px-Glendalough.jpg"
        icon: image
      qos: 1
      retain: True
      cache: True

    - title: Image
      type: image
      subscribe: example/image/src
      height: 300px

  # --- group: Widget Button and Text ---
  - title: Buttons & Text
    name: widget_button_text
    widgets:

    - title: In
      type: button
      publish: widget/text
      text: "Hello"
      payload: "HELLO"
      qos: 1

    - title: In
      type: button
      publish: widget/text
      text: "World"
      payload: "WORLD"
      qos: 1

    - title: Text
      type: text
      subscribe: widget/text
      color: magenta

  # --- group: Widget Light ---
  - title: Light
    name: widget_light
    widgets:
    - title: In
      type: button
      publish: widget/light
      text: "On"
      payload: "true"
      qos: 1

    - title: In
      type: button
      publish: widget/light
      text: "Off"
      payload: "false"
      qos: 1

    - title: In
      type: button
      publish: widget/light
      text: "Other"
      payload: "other"
      confirm: "Really?"
      qos: 1

    - title: Light
      type: light
      subscribe: widget/light
      values:
        - payload: "false"
          text: OFF
        - payload: "true"
          text: ON
          color: yellow

  # --- group: Widget Switch ---
  - title: Switch
    name: widget_switch
    widgets:
    - title: In
      type: button
      publish: widget/switch/rx
      text: "On"
      payload: "true"
      qos: 1

    - title: In
      type: button
      publish: widget/switch/rx
      text: "Off"
      payload: "false"
      qos: 1

    - title: In
      type: button
      publish: widget/switch/rx
      text: "Other"
      payload: "other"
      confirm: "Really?"
      qos: 1

    - title: Switch
      type: switch
      subscribe: widget/switch/rx
      publish: widget/switch/tx
      values:
      - text: "Off"
        payload: "false"
      - text: "On"
        payload: "true"
      qos: 1
      cache: True

    - title: "Out"
      type: text
      subscribe: widget/switch/tx
      cache: True

  # --- group: Widget Gauge ---
  - title: Gauge
    name: widget_gauge
    widgets:
    - title: In
      type: slider
      publish: widget/gauge
      subscribe: widget/gauge
      ranges:
      - range: [-50, 50]
      qos: 1

    - title: Gauge
      type: gauge
      subscribe: widget/gauge
      icon: health_and_safety
      ranges:
      - range: [-50, -20]
        text: Nasty
        color: "blue"
        icon: warning
      - range: [-20, 5]
        text: Skiing
        color: "green"
        icon: downhill_skiing
      - range: [5, 20]
        text: Reading
        color: "yellow"
        icon: import_contacts
      - range: [20, 35]
        text: Beach
        color: "orange"
        icon: beach_access
      - range: [35, 50]
        text: Hot
        color: "red"
        icon: wb_sunny
      cache: True

  # --- group: Widget Slider ---
  - title: Slider
    name: widget_slider
    widgets:
    - title: In
      type: slider
      publish: widget/slider/rx
      subscribe: widget/slider/rx
      ranges:
      - range: [0, 100]
      qos: 1

    - title: Slider
      type: slider
      publish: widget/slider/tx
      subscribe: widget/slider/rx
      ranges:
      - range: [0, 30]
        text: "Empty"
        icon: battery_std
        color: "#b03c02"
      - range: [30, 60]
        text: "Low"
        icon: battery_std
        color: "#b08a02"
      - range: [60, 80]
        text: "Medium"
        icon: battery_std
        color: "#82b002"
      - range: [80, 100]
        text: "Good"
        icon: battery_std
        color: "#02b002"
      qos: 1
      cache: True

    - title: Out
      type: text
      subscribe: widget/slider/tx
      icon: health_and_safety

  # --- group: Widget Slider (live) ---
  - title: Slider (live)
    name: widget_slider_live
    widgets:
    - title: In
      type: slider
      publish: widget/slider_live/rx
      subscribe: widget/slider_live/rx
      live: True
      ranges:
      - range: [0, 100]
      qos: 1

    - title: Slider
      type: slider
      publish: widget/slider_live/tx
      subscribe: widget/slider_live/rx
      live: True
      ranges:
      - range: [0, 30]
        text: "Empty"
        icon: battery_std
        color: "#b03c02"
      - range: [30, 60]
        text: "Low"
        icon: battery_std
        color: "#b08a02"
      - range: [60, 80]
        text: "Medium"
        icon: battery_std
        color: "#82b002"
      - range: [80, 100]
        text: "Good"
        icon: battery_std
        color: "#02b002"
      qos: 1
      cache: True

    - title: Out
      type: text
      subscribe: widget/slider_live/tx
      icon: health_and_safety

  # --- group: Image ---
  - title: Select
    name: widget_select
    widgets:

    - title: In
      type: button
      publish: widget/select/rx
      text: "Ireland"
      payload: "Guinness"
      qos: 1

    - title: In
      type: button
      publish: widget/select/rx
      text: "Venice"
      payload: "Gondola"
      qos: 1

    - title: In
      type: button
      publish: widget/select/rx
      text: "Cape Town"
      payload: "Mountain"
      qos: 1

    - title: In
      type: button
      publish: widget/select/rx
      text: "Other"
      payload: "other"
      confirm: "Really?"
      qos: 1

    - title: Select
      type: select
      subscribe: widget/select/rx
      publish: widget/select/tx
      values:
      - text: "Ireland"
        payload: "Guinness"
        icon: sports_bar
        color: green
      - text: "Venice"
        payload: "Gondola"
        icon: rowing
        color: red
      - text: "Cape Town"
        payload: "Mountain"
        icon: landscape
        color: cyan
      - text: "Confirm"
        payload: "confirm"
        icon: help
        color: orange
        confirm: "Really?"
      qos: 1
      cache: True

    - title: "Out"
      type: text
      subscribe: widget/select/tx
      cache: True


  # --- group: Widget Image ---
  - title: Image
    name: widget_image
    widgets:
    - title: Image
      type: image
      src: "https://d15omoko64skxi.cloudfront.net/wp-content/uploads/2018/01/beeple-768x768.jpg"
      height: 300px

  # --- group: Widget Iframe ---
  - title: Iframe
    name: widget_iframe
    widgets:
    - title: Iframe
      type: iframe
      attr:
        src: https://www.example.com
        width: 480px
        height: 315px
        title: Example

  # -- group: Reuse
  - title: Widget Re-use
    name: widget_reuse
    widgets:
    - title: Ref SW1
      ref: sw1
      type: switch
      publish: widget/reuse/sw1
      subscribe: widget/reuse/sw1
      values:
      - text: "No"
        payload: "OFF"
        color: '#F04040'
      - text: "Yes"
        payload: "ON"
        color: '#40F000'
      qos: 1
      cache: True

    - ref: sw1
    - ref: sw1
